CREATE TABLE book_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id BIGINT                                  NOT NULL,
    book_id  BIGINT,
    quantity INT                                     NOT NULL,
    price    DECIMAL                                 NOT NULL,
    CONSTRAINT pk_book_items PRIMARY KEY (id)
);

CREATE TABLE books
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    genre            VARCHAR(255)                            NOT NULL,
    age_group        VARCHAR(255)                            NOT NULL,
    price            DECIMAL                                 NOT NULL,
    publication_year date                                    NOT NULL,
    author           VARCHAR(255)                            NOT NULL,
    number_of_pages  INT                                     NOT NULL,
    characteristics  VARCHAR(2000)                           NOT NULL,
    description      VARCHAR(5000),
    language         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE clients
(
    id      BIGINT  NOT NULL,
    balance DECIMAL NOT NULL,
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id         BIGINT       NOT NULL,
    phone      VARCHAR(255) NOT NULL,
    birth_date date         NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id   BIGINT                                  NOT NULL,
    employee_id BIGINT,
    order_date  TIMESTAMP                               NOT NULL,
    price       DECIMAL                                 NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id   BIGINT NOT NULL,
    role_name VARCHAR(255)
);

CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    is_locked BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE books
    ADD CONSTRAINT uc_books_name UNIQUE (name);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_phone UNIQUE (phone);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE book_items
    ADD CONSTRAINT FK_BOOK_ITEMS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE book_items
    ADD CONSTRAINT FK_BOOK_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE clients
    ADD CONSTRAINT FK_CLIENTS_ON_ID FOREIGN KEY (id) REFERENCES users (id);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_ID FOREIGN KEY (id) REFERENCES users (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES clients (id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);